import '@/assets/scss/global.scss';
import type { Metadata } from 'next';
import { ClienContainer } from '@/misc/client-container';
import { SessionProvider } from '@/misc/session/session-provider';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ClienContainer>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ClienContainer>
      </body>
    </html>
  );
}
