import '@/assets/scss/global.scss';
import '@/misc/global/global.server';
import type { Metadata } from 'next';
import { ClienContainer } from '@/misc/client-container';
import { SessionProvider } from '@/misc/session/session-provider';
import { initServerData } from '@/misc/server';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  initServerData();

  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ClienContainer>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ClienContainer>
      </body>
    </html>
  );
}
