import type { Metadata } from 'next';
import { ClienContainer } from '@/misc/client-container';
import '@/assets/scss/global.scss';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ClienContainer>
          {children}
        </ClienContainer>
      </body>
    </html>
  );
}
